Fix error C1128 for x86 debug builds.
The test\cctest\gay-precision.cc file will cause below error
for Visual Studio 2013.

`fatal error C1128: number of sections exceeded
object file format limit : compile with /bigobj`